# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 03:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0002_auto_20170224_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='name',
            field=models.CharField(max_length=40, unique=True, verbose_name='name'),
        ),
    ]
