# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 16:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0003_auto_20170225_0340'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='channel',
            options={'verbose_name': 'channel', 'verbose_name_plural': 'channels'},
        ),
    ]
